const FIJIAN_WORDS = [
  {
    id: 1,
    word: "bula",
    phonetic: "mbula",
    partOfSpeech: "exclamation / greeting",
    fijianDef: "Isa, ko ira na noda veiwekani e taura tiko na vosa oqo me veivosaki kina — e dua na vosa e vakayacori taka na marau, na bula vinaka, ka na lomalomai.",
    englishDef: "Hello; the most common Fijian greeting expressing joy, life, and wellbeing. Used at any time of day.",
    example: "Bula! O cei na yacamu?",
    exampleTranslation: "Hello! What is your name?",
    category: "greetings",
    tags: ["everyday", "essential"]
  },
  {
    id: 2,
    word: "vinaka",
    phonetic: "vinaka",
    partOfSpeech: "adjective / exclamation",
    fijianDef: "Vosa e vakayacori taka na loloma, na lomalomai, ka na vakavinavinakataki. E kaya tu me \"vakavinavinakataki\" ka me \"vinaka dina\".",
    englishDef: "Good; thank you; well done. One of the most versatile Fijian words, used both as thanks and as a general positive affirmation.",
    example: "Vinaka vakalevu!",
    exampleTranslation: "Thank you very much!",
    category: "greetings",
    tags: ["essential", "everyday"]
  },
  {
    id: 3,
    word: "ni sa bula",
    phonetic: "ni sa mbula",
    partOfSpeech: "phrase / greeting",
    fijianDef: "Dua na vosa ni veivosaki e vakayacori taka na veivakadewataki ka na vakarokoroko. Ko 'ni sa' e vakayacori taka na veirogorogoci ka na vakavinavinakataki.",
    englishDef: "A formal or respectful form of greeting meaning 'greetings to you'. More respectful than 'bula' alone, often used when addressing elders or in formal settings.",
    example: "Ni sa bula vinaka!",
    exampleTranslation: "Good greetings to you!",
    category: "greetings",
    tags: ["formal", "essential"]
  },
  {
    id: 4,
    word: "kana",
    phonetic: "kana",
    partOfSpeech: "verb",
    fijianDef: "Ko kana e kaya me rava kina na kakana — na cakacaka e mai taka na bula ni tamata. E vakayacori taka na loloma ki na kakana ka na kana vinaka.",
    englishDef: "To eat. A fundamental Fijian verb describing the act of eating food. Often used in invitations to share meals.",
    example: "Mai kana!",
    exampleTranslation: "Come and eat!",
    category: "food",
    tags: ["everyday", "essential"]
  },
  {
    id: 5,
    word: "vale",
    phonetic: "vale",
    partOfSpeech: "noun",
    fijianDef: "Ko vale e kaya na yavu ni bula ni tamata — na vanua e nodrau nodrau me ra bula kina na matavuvale. E dodonu me vakalekaleka ka vakayaco vinaka.",
    englishDef: "House; home. The center of Fijian communal life where family gathers, guests are welcomed, and ceremonies take place.",
    example: "O iko e nomu vale?",
    exampleTranslation: "Is this your house?",
    category: "places",
    tags: ["everyday", "essential"]
  },
  {
    id: 6,
    word: "yaqona",
    phonetic: "yangona",
    partOfSpeech: "noun",
    fijianDef: "Ko yaqona e dua na kau tabu e vakayacori taka na veivakatauyavutaki ni Viti. E cakava na bilo ni yaqona me veivakatauyavutaki ka vakarokorokotaki na turaga, ka dau vakayacori na veivakatauyavutaki ni vanua.",
    englishDef: "Kava; the ceremonial drink made from the root of the pepper plant (Piper methysticum). Central to Fijian culture, used in ceremonies, welcoming chiefs, and social gatherings.",
    example: "Me soli na yaqona ki na turaga.",
    exampleTranslation: "Present the kava to the chief.",
    category: "culture",
    tags: ["cultural", "ceremony", "essential"]
  },
  {
    id: 7,
    word: "tavioka",
    phonetic: "tavioka",
    partOfSpeech: "noun",
    fijianDef: "Ko tavioka e dua na kakana e soli mai na wai ni vuaka — e dau kakana e Viti ka dau vakasagataki kei na ika, kei na sipi, ka na ibe.",
    englishDef: "Cassava (tapioca). The staple food of Fiji, a starchy root vegetable that is boiled, baked in a lovo (earth oven), or used in sweets.",
    example: "Au via kana tavioka.",
    exampleTranslation: "I want to eat cassava.",
    category: "food",
    tags: ["food", "everyday"]
  },
  {
    id: 8,
    word: "gone",
    phonetic: "ngone",
    partOfSpeech: "noun",
    fijianDef: "Ko gone e vakayacori taka na tamata yalewa se tagane e sa tekivu tu mai na lailai ka sa levu cake. E vakayacori na marau ka na veisomoni ni matavuvale.",
    englishDef: "Child; children. Used to refer to young people fondly. Children hold a central place in Fijian family life and are the responsibility of the whole community.",
    example: "Na gone e dau marau.",
    exampleTranslation: "Children are always happy.",
    category: "people",
    tags: ["family", "everyday"]
  },
  {
    id: 9,
    word: "yalewa",
    phonetic: "yalewa",
    partOfSpeech: "noun / adjective",
    fijianDef: "Ko yalewa e vakayacori taka na vakamaroroi ni yalewa — na ivakatagedegede ni tamata yalewa. E dau vakayacori na kaukauwa ka na lomalomai ni yalewa.",
    englishDef: "Woman; female. Used to describe a woman or girl. Fijian women are highly respected and play vital roles in family and community ceremonies.",
    example: "Na yalewa e levu na kaukauwa.",
    exampleTranslation: "The woman is very strong.",
    category: "people",
    tags: ["people", "everyday"]
  },
  {
    id: 10,
    word: "tagane",
    phonetic: "tangane",
    partOfSpeech: "noun / adjective",
    fijianDef: "Ko tagane e vakayacori taka na vakamaroroi ni tagane — na ivakatagedegede ni tamata tagane. E dau vakayacori na kaukauwa ka na veivakatauyavutaki ni tagane.",
    englishDef: "Man; male. Used to describe a man or boy. Men traditionally hold roles as chiefs, warriors, and fishermen in Fijian society.",
    example: "Na tagane e dau soli na ika.",
    exampleTranslation: "The man often gives fish.",
    category: "people",
    tags: ["people", "everyday"]
  },
  {
    id: 11,
    word: "moce",
    phonetic: "mothe",
    partOfSpeech: "exclamation / verb",
    fijianDef: "Ko moce e vakayacori taka na veimocetaki — na vosa ni vakabibi ni bogi. E dau vakayacori na vakailoga ni veivaqarai.",
    englishDef: "Goodbye; goodnight; sleep. Used as a farewell, especially at night. Also means 'to sleep' as a verb.",
    example: "Moce! Ni sa bogi.",
    exampleTranslation: "Goodbye! It is night.",
    category: "greetings",
    tags: ["everyday", "essential"]
  },
  {
    id: 12,
    word: "io",
    phonetic: "io",
    partOfSpeech: "particle",
    fijianDef: "Ko io e vakayacori taka na veivakadewataki — na vosa ni talia me dua na kena ivakarau. E leqa cake mai na 'sega'.",
    englishDef: "Yes. The standard affirmative response in Fijian. Simple and clear — used in all contexts formal and informal.",
    example: "Io, au via lako.",
    exampleTranslation: "Yes, I want to go.",
    category: "basics",
    tags: ["essential", "everyday"]
  },
  {
    id: 13,
    word: "sega",
    phonetic: "senga",
    partOfSpeech: "particle",
    fijianDef: "Ko sega e vakayacori taka na sega ni talia — na vosa ni kakua. E leqa cake mai na 'io'. E dau vakayacori tu me 'sega ni rawa' se 'sega vakadua'.",
    englishDef: "No; not. The standard negative in Fijian. Used alone or combined: 'sega vakadua' (absolutely not), 'sega ni rawa' (impossible).",
    example: "Sega, au sega ni via kana.",
    exampleTranslation: "No, I don't want to eat.",
    category: "basics",
    tags: ["essential", "everyday"]
  },
  {
    id: 14,
    word: "lako",
    phonetic: "lako",
    partOfSpeech: "verb",
    fijianDef: "Ko lako e vakayacori taka na cakacaka ni toso mai dua na vanua ki na dua tale. E dau vakayacori me 'lako mai' (come) se 'lako yani' (go there).",
    englishDef: "To go; to walk. Used to indicate movement or travel. Direction particles 'mai' (toward) and 'yani' (away) are commonly attached.",
    example: "Au na lako ki na makete.",
    exampleTranslation: "I will go to the market.",
    category: "verbs",
    tags: ["everyday", "essential"]
  },
  {
    id: 15,
    word: "mai",
    phonetic: "mai",
    partOfSpeech: "directional particle",
    fijianDef: "Ko mai e vakayacori taka na tosoiaki ki na vanua e tiko kina na tamata e veivosaki kina — e tukutuku mai 'lesu mai', 'lako mai'.",
    englishDef: "Come; toward (the speaker). A directional particle indicating movement toward the speaker or current location. Very commonly used in invitations.",
    example: "Mai tiko!",
    exampleTranslation: "Come stay / Come here!",
    category: "basics",
    tags: ["everyday", "essential"]
  },
  {
    id: 16,
    word: "yani",
    phonetic: "yani",
    partOfSpeech: "directional particle",
    fijianDef: "Ko yani e vakayacori taka na tosoiaki ki na vanua tale e sega ni tiko kina na tamata e veivosaki — e tukutuku yani 'lako yani', 'lesu yani'.",
    englishDef: "Go; away (from the speaker). The directional opposite of 'mai', indicating movement away. Often paired with verbs of motion.",
    example: "Lako yani ki vale.",
    exampleTranslation: "Go to the house.",
    category: "basics",
    tags: ["everyday"]
  },
  {
    id: 17,
    word: "dua",
    phonetic: "ndua",
    partOfSpeech: "number / article",
    fijianDef: "Ko dua e vakayacori taka na ivakarau ni ivolatukutuku ka e kaya tu na 'e dua' (one). E dau vakayacori tu me na iwiliwili na tamata se ka.",
    englishDef: "One; a/an (indefinite article). The number one and also the indefinite article in Fijian. 'E dua na gone' = 'a child'.",
    example: "E dua na vale levu.",
    exampleTranslation: "One big house.",
    category: "numbers",
    tags: ["everyday", "essential"]
  },
  {
    id: 18,
    word: "rua",
    phonetic: "rua",
    partOfSpeech: "number",
    fijianDef: "Ko rua e vakayacori taka na ivakarau ni ivolatukutuku e rua (two). E dau vakavinakataki ki na veivosi ni ika, ni gone, ka na yau rua.",
    englishDef: "Two. The number two, used in counting people, objects, and time.",
    example: "E rua na ika au a kune.",
    exampleTranslation: "I caught two fish.",
    category: "numbers",
    tags: ["everyday"]
  },
  {
    id: 19,
    word: "tolu",
    phonetic: "tolu",
    partOfSpeech: "number",
    fijianDef: "Ko tolu e vakayacori taka na ivakarau ni ivolatukutuku e tolu (three).",
    englishDef: "Three. The number three.",
    example: "E tolu na gone e lako.",
    exampleTranslation: "Three children are going.",
    category: "numbers",
    tags: ["everyday"]
  },
  {
    id: 20,
    word: "va",
    phonetic: "va",
    partOfSpeech: "number",
    fijianDef: "Ko va e vakayacori taka na ivakarau ni ivolatukutuku e va (four).",
    englishDef: "Four. The number four.",
    example: "E va na siga ni macawa.",
    exampleTranslation: "It is four days of the week.",
    category: "numbers",
    tags: ["everyday"]
  },
  {
    id: 21,
    word: "lima",
    phonetic: "lima",
    partOfSpeech: "number / noun",
    fijianDef: "Ko lima e vakayacori taka na ivakarau ni ivolatukutuku e lima (five), ka e vakayacori tu na nima ni tamata.",
    englishDef: "Five; hand. The number five and also the word for hand — reflecting the natural counting tool.",
    example: "E lima na nima ni tamata.",
    exampleTranslation: "A person has five fingers / a hand.",
    category: "numbers",
    tags: ["everyday", "body"]
  },
  {
    id: 22,
    word: "ono",
    phonetic: "ono",
    partOfSpeech: "number",
    fijianDef: "Ko ono e vakayacori taka na ivakarau ni ivolatukutuku e ono (six).",
    englishDef: "Six. The number six.",
    example: "Au a tawa ono na ika.",
    exampleTranslation: "I caught six fish.",
    category: "numbers",
    tags: ["everyday"]
  },
  {
    id: 23,
    word: "vitu",
    phonetic: "vitu",
    partOfSpeech: "number",
    fijianDef: "Ko vitu e vakayacori taka na ivakarau ni ivolatukutuku e vitu (seven).",
    englishDef: "Seven. The number seven.",
    example: "E vitu na siga ni macawa.",
    exampleTranslation: "There are seven days in a week.",
    category: "numbers",
    tags: ["everyday"]
  },
  {
    id: 24,
    word: "walu",
    phonetic: "walu",
    partOfSpeech: "number",
    fijianDef: "Ko walu e vakayacori taka na ivakarau ni ivolatukutuku e walu (eight).",
    englishDef: "Eight. The number eight.",
    example: "E walu na kaloko.",
    exampleTranslation: "It is eight o'clock.",
    category: "numbers",
    tags: ["everyday"]
  },
  {
    id: 25,
    word: "ciwa",
    phonetic: "thiwa",
    partOfSpeech: "number",
    fijianDef: "Ko ciwa e vakayacori taka na ivakarau ni ivolatukutuku e ciwa (nine).",
    englishDef: "Nine. The number nine.",
    example: "E ciwa na kaloko ni mataka.",
    exampleTranslation: "It is nine o'clock in the morning.",
    category: "numbers",
    tags: ["everyday"]
  },
  {
    id: 26,
    word: "tini",
    phonetic: "tini",
    partOfSpeech: "number",
    fijianDef: "Ko tini e vakayacori taka na ivakarau ni ivolatukutuku e tini (ten).",
    englishDef: "Ten. The number ten.",
    example: "E tini na dola.",
    exampleTranslation: "It is ten dollars.",
    category: "numbers",
    tags: ["everyday"]
  },
  {
    id: 27,
    word: "matavuvale",
    phonetic: "matavuvale",
    partOfSpeech: "noun",
    fijianDef: "Ko matavuvale e vakayacori taka na veivakatauyavutaki ni tamata e bula vata — na tamana, na tina, ka na gone. Na matavuvale e na noda kaukauwa.",
    englishDef: "Family. The cornerstone of Fijian society. Encompasses immediate and extended family — in Fijian culture, the community is family.",
    example: "Ko au e loloma tiko ki na noqu matavuvale.",
    exampleTranslation: "I love my family.",
    category: "people",
    tags: ["family", "essential"]
  },
  {
    id: 28,
    word: "tamana",
    phonetic: "tamana",
    partOfSpeech: "noun",
    fijianDef: "Ko tamana e vakayacori taka na tamata tagane e tama tiko na gone — na tamana ni matavuvale. E dau vakarokorokotaki kei na itukutuku.",
    englishDef: "Father. The male parent. Fathers are respected leaders of the household in Fijian tradition.",
    example: "Ko noqu tamana e turaga vinaka.",
    exampleTranslation: "My father is a good chief/man.",
    category: "people",
    tags: ["family", "everyday"]
  },
  {
    id: 29,
    word: "tina",
    phonetic: "tina",
    partOfSpeech: "noun",
    fijianDef: "Ko tina e vakayacori taka na tamata yalewa e tina tiko na gone — na tina ni matavuvale. E dau vakayacori na loloma ka na cakacaka ni matavuvale.",
    englishDef: "Mother. The female parent. Mothers are highly revered in Fijian culture for their nurturing role and strength.",
    example: "Ko noqu tina e marau tiko.",
    exampleTranslation: "My mother is always happy.",
    category: "people",
    tags: ["family", "everyday"]
  },
  {
    id: 30,
    word: "taci",
    phonetic: "tathi",
    partOfSpeech: "noun",
    fijianDef: "Ko taci e vakayacori taka na vakaiwase ni veiwekani — ko ira na gone ni tamana tauvu, e gone yalewa se tagane e levu cake mai.",
    englishDef: "Younger sibling. The Fijian kinship term for a younger brother or sister. Fijian kinship terms are nuanced and depend on relative age and gender.",
    example: "Ko noqu taci e gone lailai.",
    exampleTranslation: "My younger sibling is small.",
    category: "people",
    tags: ["family", "everyday"]
  },
  {
    id: 31,
    word: "tuaka",
    phonetic: "tuaka",
    partOfSpeech: "noun",
    fijianDef: "Ko tuaka e vakayacori taka na gone tagane e levu cake — na veitacini gone tagane. E dau vakarokorokotaki ka vakaitavi ena veivakatauyavutaki.",
    englishDef: "Older brother (for a male speaker). The term used by a man to refer to his older brother, reflecting the importance of birth order in Fijian society.",
    example: "Ko noqu tuaka e dau tawa ika.",
    exampleTranslation: "My older brother often fishes.",
    category: "people",
    tags: ["family"]
  },
  {
    id: 32,
    word: "ika",
    phonetic: "ika",
    partOfSpeech: "noun",
    fijianDef: "Ko ika e dua na manu ni wai — e dau kune na tagane ena waqawaqa. Na ika e kakana vinaka ka dau soli ena veivakatauyavutaki.",
    englishDef: "Fish. A staple of the Fijian diet and a central part of coastal and island life. Fishing is a traditional skill and source of pride.",
    example: "Au a kune na ika levu.",
    exampleTranslation: "I caught a big fish.",
    category: "food",
    tags: ["food", "everyday"]
  },
  {
    id: 33,
    word: "wai",
    phonetic: "wai",
    partOfSpeech: "noun",
    fijianDef: "Ko wai e vakayacori taka na waiwai — na ka e tara na bula ni tamata. E dau vakayacori tu na wainimate (medicine) ka na wai ni vanua.",
    englishDef: "Water. Essential for life and found abundantly in Fiji's rivers, rain, and seas. Also used in compound words like 'wainimate' (medicine).",
    example: "Au via dringi wai.",
    exampleTranslation: "I want to drink water.",
    category: "nature",
    tags: ["everyday", "essential"]
  },
  {
    id: 34,
    word: "dela",
    phonetic: "ndela",
    partOfSpeech: "noun",
    fijianDef: "Ko dela e vakayacori taka na sausau ni ka — na dela ni kete, na dela ni ibi, ka na dela ni tamata (ulu).",
    englishDef: "Top; head of something. Used for the top of a basket, the head (when referring to the crown), or the summit of a hill.",
    example: "Tiko e dela ni uciwai.",
    exampleTranslation: "It is at the top of the waterfall.",
    category: "descriptive",
    tags: ["everyday"]
  },
  {
    id: 35,
    word: "loma",
    phonetic: "loma",
    partOfSpeech: "noun / preposition",
    fijianDef: "Ko loma e vakayacori taka na lomaloma ni ka — na kena loma. E dau vakayacori tu me 'e loma ni vale' (inside the house). E vakayacori tu na 'lomana' (heart/feeling).",
    englishDef: "Inside; middle; center; heart. Both a spatial preposition and an emotional term. 'Loma' also refers to the inner feelings and emotions of a person.",
    example: "E loma ni vale e ci vinaka.",
    exampleTranslation: "Inside the house it is cool.",
    category: "basics",
    tags: ["everyday", "essential"]
  },
  {
    id: 36,
    word: "veiqaravi",
    phonetic: "veinggaravi",
    partOfSpeech: "noun / verb",
    fijianDef: "Ko veiqaravi e vakayacori taka na cakacaka ni vakarokoroko ka na veivakaitavi — na soli nia.",
    englishDef: "Service; to serve; worship. Refers to acts of service, worship, or helping others. Used in both religious and community contexts.",
    example: "Na veiqaravi e loloma.",
    exampleTranslation: "Service is love.",
    category: "culture",
    tags: ["cultural", "spiritual"]
  },
  {
    id: 37,
    word: "loloma",
    phonetic: "loloma",
    partOfSpeech: "noun / verb",
    fijianDef: "Ko loloma e vakayacori taka na nona lomana na tamata ki na oya tale. Na loloma e levu cake mai na nomu nanuma.",
    englishDef: "Love; compassion; kindness. One of the most important values in Fijian culture, encompassing love, care, compassion, and generosity.",
    example: "Au lomana kemuni.",
    exampleTranslation: "I love you (plural).",
    category: "emotions",
    tags: ["essential", "cultural"]
  },
  {
    id: 38,
    word: "marau",
    phonetic: "marau",
    partOfSpeech: "adjective / noun",
    fijianDef: "Ko marau e vakayacori taka na loma vinaka — na vakayacori taka na marautaki ka na dredre ni vakadinadina.",
    englishDef: "Happy; happiness; joyful. Describes a state of joy and contentment. Fijians are known worldwide for their warm smiles and marau.",
    example: "Au marau sara vakalevu.",
    exampleTranslation: "I am very, very happy.",
    category: "emotions",
    tags: ["everyday", "essential"]
  },
  {
    id: 39,
    word: "dredre",
    phonetic: "ndrendre",
    partOfSpeech: "adjective / verb",
    fijianDef: "Ko dredre e vakayacori taka na ka e dredre — na ka e caka e dua na drosivaki. E leqa cake mai na 'rawarawa'.",
    englishDef: "Difficult; hard; to be difficult. Describes challenges or hard tasks. The opposite is 'rawarawa' (easy).",
    example: "Na vosa vakaviti e dredre vaka'au.",
    exampleTranslation: "The Fijian language is a bit difficult for me.",
    category: "descriptive",
    tags: ["everyday"]
  },
  {
    id: 40,
    word: "rawarawa",
    phonetic: "rawarawa",
    partOfSpeech: "adjective",
    fijianDef: "Ko rawarawa e vakayacori taka na ka e lailai na kena oca — na ka e caka rawarawa. E leqa cake mai na 'dredre'.",
    englishDef: "Easy; simple. The positive counterpart to 'dredre'. Used to encourage or reassure others.",
    example: "Io, e rawarawa!",
    exampleTranslation: "Yes, it is easy!",
    category: "descriptive",
    tags: ["everyday"]
  },
  {
    id: 41,
    word: "levu",
    phonetic: "levu",
    partOfSpeech: "adjective",
    fijianDef: "Ko levu e vakayacori taka na ka e levu — na lekaleka ni ka. E dau vakayacori tu me 'vinaka vakalevu' (thank you very much).",
    englishDef: "Big; large; much; many. A very common adjective with multiple meanings depending on context. 'Vakalevu' = very much.",
    example: "Na vale e levu.",
    exampleTranslation: "The house is big.",
    category: "descriptive",
    tags: ["everyday", "essential"]
  },
  {
    id: 42,
    word: "lailai",
    phonetic: "lailai",
    partOfSpeech: "adjective",
    fijianDef: "Ko lailai e vakayacori taka na ka e lailai — e leqa cake mai na 'levu'. E dau vakayacori ki na gone, ki na ika, ka na kena ivolatukutuku.",
    englishDef: "Small; little; young. The opposite of 'levu'. Also used to indicate youth or smallness affectionately.",
    example: "E dua na gone lailai.",
    exampleTranslation: "A little child.",
    category: "descriptive",
    tags: ["everyday", "essential"]
  },
  {
    id: 43,
    word: "lasa",
    phonetic: "lasa",
    partOfSpeech: "adjective / verb",
    fijianDef: "Ko lasa e vakayacori taka na kakana e lasa — na kena ka e kau na marau ni kana. E dau vakayacori ki na ika vakasoso, ki na ika vakakuro, ka na ibe.",
    englishDef: "Tasty; delicious; to taste good. Used to describe food that is enjoyable to eat. A compliment to any cook.",
    example: "Isa, e lasa na ika!",
    exampleTranslation: "Wow, the fish is delicious!",
    category: "food",
    tags: ["food", "everyday"]
  },
  {
    id: 44,
    word: "vakasama",
    phonetic: "vakasama",
    partOfSpeech: "verb",
    fijianDef: "Ko vakasama e vakayacori taka na cakacaka ni nanuma — na isema ni loma. E dau vakayacori ki na tabana ni vuli ka na veiqaravi.",
    englishDef: "To think; to consider. The act of thinking or reflecting. Used in discussions, education, and spiritual contexts.",
    example: "Au sa vakasama vinaka.",
    exampleTranslation: "I have thought carefully.",
    category: "verbs",
    tags: ["everyday"]
  },
  {
    id: 45,
    word: "kilaka",
    phonetic: "kilaka",
    partOfSpeech: "verb",
    fijianDef: "Ko kilaka e vakayacori taka na veikila — na vakadinadina ni ka. E dau vakayacori ki na vosa, ki na tamata, ka na itikotiko.",
    englishDef: "To know; to recognize. The act of knowing someone or something. 'Au kilaka iko' means 'I know you'.",
    example: "Au kilaka na yacamu.",
    exampleTranslation: "I know your name.",
    category: "verbs",
    tags: ["everyday"]
  },
  {
    id: 46,
    word: "rogoca",
    phonetic: "ronggotha",
    partOfSpeech: "verb",
    fijianDef: "Ko rogoca e vakayacori taka na veirogorogoci — na tauriva ni vosa se na nakiti. E dau vakayacori tu me vakatauva na valataki.",
    englishDef: "To hear; to listen; to understand (in some dialects). The act of hearing or listening carefully.",
    example: "Rogoca mai!",
    exampleTranslation: "Listen to this!",
    category: "verbs",
    tags: ["everyday"]
  },
  {
    id: 47,
    word: "raica",
    phonetic: "raitha",
    partOfSpeech: "verb",
    fijianDef: "Ko raica e vakayacori taka na veikana — na tauriva ni ka e yaco. E dau vakayacori tu me 'raica mai' (look here).",
    englishDef: "To see; to look at; to watch. The act of seeing or observing something.",
    example: "Au a raica na vuravura vinaka.",
    exampleTranslation: "I saw the beautiful world.",
    category: "verbs",
    tags: ["everyday"]
  },
  {
    id: 48,
    word: "vakasuka",
    phonetic: "vakasuka",
    partOfSpeech: "verb / adjective",
    fijianDef: "Ko vakasuka e vakayacori taka na ka e suka — na lolo ni ka. E dau vakayacori ki na kana e suka ka na waiwai e suka.",
    englishDef: "Sweet; to sweeten. Describes food or drink with a sweet taste. Fiji's sugarcane industry makes this word very apt.",
    category: "food",
    tags: ["food", "taste"]
  },
  {
    id: 49,
    word: "loto",
    phonetic: "loto",
    partOfSpeech: "noun / verb",
    fijianDef: "Ko loto e vakayacori taka na nanuma ni loma — na kena loto. E dau vakayacori tu me 'loto vinaka' (willing heart) ka na 'loto levu' (generosity).",
    englishDef: "Will; heart; to wish; to want. Refers to desire, willingness, and the inner intentions of the heart.",
    example: "Au loto me lako.",
    exampleTranslation: "I wish to go.",
    category: "emotions",
    tags: ["everyday"]
  },
  {
    id: 50,
    word: "sota",
    phonetic: "sota",
    partOfSpeech: "verb / noun",
    fijianDef: "Ko sota e vakayacori taka na veisotaki — na veikacivi me ra sota vata na tamata. E dau vakayacori na 'sota tale' (see you again).",
    englishDef: "To meet; encounter. The act of meeting someone. 'Sota tale' is a common farewell meaning 'see you again'.",
    example: "Sota tale!",
    exampleTranslation: "See you again!",
    category: "greetings",
    tags: ["everyday", "essential"]
  },
  {
    id: 51,
    word: "uro",
    phonetic: "uro",
    partOfSpeech: "noun",
    fijianDef: "Ko uro e vakayacori taka na uro ni kakana — na kuro se tagane ni vale ni kana.",
    englishDef: "Cooking pot; food cooked in a pot. Refers to pot cooking, which is common in Fijian homes alongside the traditional lovo.",
    example: "E tiko na uro e loma ni kuro.",
    exampleTranslation: "The food is in the pot.",
    category: "food",
    tags: ["food", "household"]
  },
  {
    id: 52,
    word: "lovo",
    phonetic: "lovo",
    partOfSpeech: "noun",
    fijianDef: "Ko lovo e vakayacori taka na veivakacakacakai vakaviti — na ivakarau ni kakana e vakacakacakai mai e loma ni qele. E dau vakayacori na veivakatauyavutaki ka na meke.",
    englishDef: "Earth oven. The traditional Fijian method of cooking where food is wrapped in leaves and cooked over hot stones underground. Used for feasts and ceremonies.",
    example: "E vakacakacakai na ika e loma ni lovo.",
    exampleTranslation: "The fish is cooked in the earth oven.",
    category: "culture",
    tags: ["cultural", "food", "ceremony"]
  },
  {
    id: 53,
    word: "meke",
    phonetic: "meke",
    partOfSpeech: "noun",
    fijianDef: "Ko meke e vakayacori taka na veivakatauyavutaki ni tatatau ka na ivakatotogo vakaviti — na dolava ni vosa, na dauveivuke, ka na ivola ni matanitu.",
    englishDef: "Traditional Fijian dance and song performance. One of the most important expressions of Fijian culture, telling stories through movement, music, and costume.",
    example: "Na meke e vinaka vakalevu.",
    exampleTranslation: "The traditional dance is very beautiful.",
    category: "culture",
    tags: ["cultural", "ceremony"]
  },
  {
    id: 54,
    word: "sulu",
    phonetic: "sulu",
    partOfSpeech: "noun",
    fijianDef: "Ko sulu e vakayacori taka na isulu vakaviti — na isulu e dau cakavi na tagane ka na yalewa e Viti. E dau vakayacori na isulu vaka-itokatoka ka na sulu-i-ra.",
    englishDef: "Traditional Fijian wrap/skirt. The traditional garment worn by both men and women. The 'sulu vakataga' (formal sulu) is still worn in offices, churches, and ceremonies.",
    example: "E cakava na sulu lekaleka.",
    exampleTranslation: "She/he is wearing a short sulu.",
    category: "culture",
    tags: ["cultural", "clothing"]
  },
  {
    id: 55,
    word: "tabua",
    phonetic: "tambua",
    partOfSpeech: "noun",
    fijianDef: "Ko tabua e vakayacori taka na mako ni ovisa — na yau tabu e levu na kena cavuta ena veivakatauyavutaki vakaviti. E dau soli na tabua me vakarokoroko na turaga.",
    englishDef: "Sperm whale tooth. The most sacred and valuable ceremonial gift in Fijian society. Presented at weddings, funerals, negotiations, and to chiefs as the highest form of respect.",
    example: "Na tabua e yau tabu vakalevu.",
    exampleTranslation: "The whale tooth is very sacred.",
    category: "culture",
    tags: ["cultural", "ceremony", "sacred"]
  },
  {
    id: 56,
    word: "turaga",
    phonetic: "turanga",
    partOfSpeech: "noun",
    fijianDef: "Ko turaga e vakayacori taka na tamata e levu na kena itavi — na matai ni vanua, na nona igusukovi na matanitu. E dau vakayacori na 'turaga ni koro' (village chief).",
    englishDef: "Chief; lord; master. A person of chiefly rank. Fijian society has a well-defined chiefly system (mataqali) that remains influential today.",
    example: "Na turaga e vakarokorokotaki.",
    exampleTranslation: "The chief is respected.",
    category: "culture",
    tags: ["cultural", "society", "essential"]
  },
  {
    id: 57,
    word: "koro",
    phonetic: "koro",
    partOfSpeech: "noun",
    fijianDef: "Ko koro e vakayacori taka na itikotiko ni tamata — na noda vanua ni bula. E tiko kina na vale, na vale ni lotu, ka na rara.",
    englishDef: "Village. The basic unit of Fijian community life. A koro typically has a chief, communal meeting house (bure), and shared land.",
    example: "Ko au e noqu koro e Suva.",
    exampleTranslation: "My village is near Suva.",
    category: "places",
    tags: ["everyday", "essential"]
  },
  {
    id: 58,
    word: "bure",
    phonetic: "mbure",
    partOfSpeech: "noun",
    fijianDef: "Ko bure e vakayacori taka na vale vakaviti — na vale ni veivakatauyavutaki ka na veivosaki ni matavuvale. E vakatutu na bure me na bula ni vanua.",
    englishDef: "Traditional Fijian thatched house / meeting house. The distinctive round or rectangular thatched buildings at the center of village life, used for ceremonies and community gatherings.",
    example: "Na bure e levu na kena vuniwai.",
    exampleTranslation: "The meeting house has a large thatched roof.",
    category: "places",
    tags: ["cultural", "architecture"]
  },
  {
    id: 59,
    word: "rara",
    phonetic: "rara",
    partOfSpeech: "noun",
    fijianDef: "Ko rara e vakayacori taka na vanua levu e loma ni koro — na itikotiko ni veivakatauyavutaki ka na cakacaka ni koro.",
    englishDef: "Village green; public grounds. The open communal space at the center of a Fijian village where ceremonies, games, and gatherings take place.",
    example: "Na gone e tauvimate e loma ni rara.",
    exampleTranslation: "The children play in the village green.",
    category: "places",
    tags: ["cultural", "everyday"]
  },
  {
    id: 60,
    word: "matanitu",
    phonetic: "matanitu",
    partOfSpeech: "noun",
    fijianDef: "Ko matanitu e vakayacori taka na noda vanua — na veivakatauyavutaki ni matanitu. Ko Viti e matanitu vinaka.",
    englishDef: "Kingdom; government; nation. Refers to the political organization of a country or chiefdom. 'Matanitu ko Viti' = the nation of Fiji.",
    example: "Ko Viti e dua na matanitu vinaka.",
    exampleTranslation: "Fiji is a good country.",
    category: "society",
    tags: ["formal", "society"]
  },
  {
    id: 61,
    word: "vuravura",
    phonetic: "vuravura",
    partOfSpeech: "noun",
    fijianDef: "Ko vuravura e vakayacori taka na noda vanua levu — na ivakarau ni tamata na kena bula. E lailai na kena cava na vuravura ka e levu na kena vinaka.",
    englishDef: "World; earth. The entire planet and everything in it. Used philosophically to discuss the breadth of existence.",
    example: "Na vuravura e vinaka.",
    exampleTranslation: "The world is beautiful.",
    category: "nature",
    tags: ["everyday"]
  },
  {
    id: 62,
    word: "vanua",
    phonetic: "vanua",
    partOfSpeech: "noun",
    fijianDef: "Ko vanua e dua na vosa levu e vakayacori taka na qele, na tamata, ka na itikotiko. Na 'vanua' e sega ni vakayacori ga na qele — e vakayacori na kena tamata, na nodra ivola, ka na nodra bula.",
    englishDef: "Land; people and place as one. One of the most profound Fijian concepts — vanua is not just land but the people, customs, traditions, and spiritual connection to that land.",
    example: "Na noda vanua e tabu.",
    exampleTranslation: "Our land is sacred.",
    category: "culture",
    tags: ["cultural", "sacred", "essential"]
  },
  {
    id: 63,
    word: "qele",
    phonetic: "ngele",
    partOfSpeech: "noun",
    fijianDef: "Ko qele e vakayacori taka na kena ivakatagedegede na qele — na vuravura e taurivaka. E dau vakayacori na veiculturali ka na veivakatauyavutaki.",
    englishDef: "Earth; soil; land (physical). The physical earth or agricultural land. Distinguished from 'vanua' which has cultural meaning.",
    example: "Na qele e ci ka vinaka na ibe.",
    exampleTranslation: "The soil is good and productive.",
    category: "nature",
    tags: ["nature", "farming"]
  },
  {
    id: 64,
    word: "draki",
    phonetic: "ndraki",
    partOfSpeech: "noun",
    fijianDef: "Ko draki e vakayacori taka na ivakatagedegede ni draki — na draki e ca se na draki vinaka. E dau vakayacori 'draki vinaka' (good weather) ka 'draki ca' (bad weather).",
    englishDef: "Weather; climate. Fiji has a tropical climate — draki is an important daily topic in island life.",
    example: "E draki vinaka nikua.",
    exampleTranslation: "The weather is good today.",
    category: "nature",
    tags: ["everyday", "nature"]
  },
  {
    id: 65,
    word: "ua",
    phonetic: "ua",
    partOfSpeech: "noun / verb",
    fijianDef: "Ko ua e vakayacori taka na ua e usi mai — na wai e sa bogi. E dau vakayacori 'sa ua' (it is raining).",
    englishDef: "Rain; to rain. Rain is vital in Fiji for agriculture and fresh water. 'Sa ua' is a common observation during the wet season.",
    example: "Sa ua ena bogi.",
    exampleTranslation: "It is raining at night.",
    category: "nature",
    tags: ["nature", "everyday"]
  },
  {
    id: 66,
    word: "siga",
    phonetic: "singa",
    partOfSpeech: "noun",
    fijianDef: "Ko siga e vakayacori taka na siga — na yabaki ni vuravura. E dau vakayacori 'ni sa siga' (good day). E vakayacori tu na 'sigatabu' (Sunday) — siga ni lotu.",
    englishDef: "Sun; day; daytime. The word for both the sun and a day. 'Ni sa siga' is a daytime greeting. Also used in days of the week.",
    example: "Na siga e cici vinaka.",
    exampleTranslation: "The sun is shining well.",
    category: "nature",
    tags: ["everyday", "essential"]
  },
  {
    id: 67,
    word: "bogi",
    phonetic: "mbonji",
    partOfSpeech: "noun",
    fijianDef: "Ko bogi e vakayacori taka na gauna ni bogi — na gauna e sega ni siga. 'Moce' e dau vakayacori ena bogi.",
    englishDef: "Night; nighttime. The opposite of 'siga'. Evenings in Fiji are often spent with family, sharing yaqona and stories.",
    example: "E bogi vinaka nikua.",
    exampleTranslation: "It is a good night tonight.",
    category: "nature",
    tags: ["everyday"]
  },
  {
    id: 68,
    word: "mataka",
    phonetic: "mataka",
    partOfSpeech: "noun",
    fijianDef: "Ko mataka e vakayacori taka na gauna ni mataka — na gauna mai na sigai ka naka. E dau vakayacori 'ni sa mataka' (good morning).",
    englishDef: "Morning. The early part of the day. 'Ni sa mataka' is the standard morning greeting.",
    example: "Ni sa mataka!",
    exampleTranslation: "Good morning!",
    category: "greetings",
    tags: ["everyday", "essential"]
  },
  {
    id: 69,
    word: "sivia",
    phonetic: "sivia",
    partOfSpeech: "adverb / adjective",
    fijianDef: "Ko sivia e vakayacori taka na ka e sivia — e levu na kena vakayacori. E dau vakayacori 'sivia sara' (too much).",
    englishDef: "Too much; excess; beyond. Used to indicate excess or something beyond a normal amount. 'Sivia sara' = way too much.",
    example: "E sivia na ua nikua.",
    exampleTranslation: "It is raining too much today.",
    category: "descriptive",
    tags: ["everyday"]
  },
  {
    id: 70,
    word: "sara",
    phonetic: "sara",
    partOfSpeech: "intensifier",
    fijianDef: "Ko sara e vakayacori taka na ka e levu na kena ivakatagedegede — na intensifier. E dau vakayacori 'vinaka sara' (very good), 'levu sara' (very large).",
    englishDef: "Very; indeed; quite. An intensifier that strengthens adjectives and verbs. 'Vinaka sara' = very good indeed.",
    example: "E vinaka sara!",
    exampleTranslation: "It is very good indeed!",
    category: "basics",
    tags: ["everyday", "essential"]
  },
  {
    id: 71,
    word: "au",
    phonetic: "au",
    partOfSpeech: "pronoun",
    fijianDef: "Ko au e vakayacori taka na tamata e veivosaki — na ivakatagedegede ni tamata e dua. 'Ko au' e kaya 'I am'.",
    englishDef: "I; me. The first-person singular pronoun. 'Ko au' = 'I am' / 'It is me'.",
    example: "Ko au ko James.",
    exampleTranslation: "I am James.",
    category: "basics",
    tags: ["everyday", "essential"]
  },
  {
    id: 72,
    word: "iko",
    phonetic: "iko",
    partOfSpeech: "pronoun",
    fijianDef: "Ko iko e vakayacori taka na tamata e veivosaki kina — na ivakatagedegede ni tamata e rua. 'Ko iko' e kaya 'you are'.",
    englishDef: "You (singular). The second-person singular pronoun. Fijian distinguishes between singular and plural 'you'.",
    example: "Ko iko e yadra vinaka.",
    exampleTranslation: "You are well.",
    category: "basics",
    tags: ["everyday", "essential"]
  },
  {
    id: 73,
    word: "koya",
    phonetic: "koya",
    partOfSpeech: "pronoun",
    fijianDef: "Ko koya e vakayacori taka na tamata e tukutukui — na ivakatagedegede ni tamata e tolu. 'Ko koya' e kaya 'he/she is'.",
    englishDef: "He; she; it (singular third person). Fijian does not distinguish grammatical gender — 'koya' is used for he, she, or it.",
    example: "Ko koya e turaga vinaka.",
    exampleTranslation: "He/she is a good chief.",
    category: "basics",
    tags: ["everyday", "essential"]
  },
  {
    id: 74,
    word: "kemuni",
    phonetic: "kemuni",
    partOfSpeech: "pronoun",
    fijianDef: "Ko kemuni e vakayacori taka na tamata levu e veivosaki kina — na ivakatagedegede ni tamata e tolu cake. E dau vakayacori ki na veikacivi.",
    englishDef: "You (plural). The second-person plural pronoun. Used when addressing a group of people, as in 'I love you all' — 'au lomana kemuni'.",
    example: "Au lomana kemuni.",
    exampleTranslation: "I love you all.",
    category: "basics",
    tags: ["everyday"]
  },
  {
    id: 75,
    word: "yadra",
    phonetic: "yandra",
    partOfSpeech: "verb / greeting",
    fijianDef: "Ko yadra e vakayacori taka na vekauta mai na moce — na veivosaki ni mataka. E dau vakayacori 'ni sa yadra' me na veivosaki ni mataka.",
    englishDef: "To wake up; good morning. 'Ni sa yadra' is a morning greeting meaning 'you have woken up' — a warm, intimate alternative to 'ni sa mataka'.",
    example: "Ni sa yadra, noqu taci!",
    exampleTranslation: "Good morning, my younger sibling!",
    category: "greetings",
    tags: ["everyday", "essential"]
  },
  {
    id: 76,
    word: "kerekere",
    phonetic: "kerekere",
    partOfSpeech: "noun / verb",
    fijianDef: "Ko kerekere e vakayacori taka na veisoli — na ivakarau ni kerei na ka mai na tamata tale. E dau vakayacori ki na veisoli ni yau, ni cakacaka, ka na veivakatauyavutaki.",
    englishDef: "Request; to ask for something from another person. A deep-rooted Fijian custom where one can request goods or assistance from community members, who are expected to give generously.",
    example: "Au kerekere na nomu veivuke.",
    exampleTranslation: "I am asking for your help.",
    category: "culture",
    tags: ["cultural", "social"]
  },
  {
    id: 77,
    word: "sevusevu",
    phonetic: "sevusevu",
    partOfSpeech: "noun",
    fijianDef: "Ko sevusevu e vakayacori taka na veisoli ni yaqona e dau vakayacori na tamata e lako yani ki na vanua tale — na ivakatagedegede ni vakarokoroko.",
    englishDef: "Gift presentation ceremony. The formal presentation of yaqona (kava) when visiting a village or entering another's home. Skipping the sevusevu is considered very disrespectful.",
    example: "Me caka na sevusevu.",
    exampleTranslation: "The gift ceremony must be performed.",
    category: "culture",
    tags: ["cultural", "ceremony", "essential"]
  },
  {
    id: 78,
    word: "talanoa",
    phonetic: "talanoa",
    partOfSpeech: "noun / verb",
    fijianDef: "Ko talanoa e vakayacori taka na veivosaki — na kena veitarokotaki na ka. E dau vakayacori ki na veivosaki ni yaqona, ki na veivosaki ni sere, ka na veitarokotaki.",
    englishDef: "Conversation; storytelling; dialogue. The Fijian practice of open, inclusive conversation, often around a bowl of yaqona. Talanoa sessions are important for conflict resolution and community decision-making.",
    example: "Me ra talanoa na tamata.",
    exampleTranslation: "Let the people have a conversation.",
    category: "culture",
    tags: ["cultural", "social"]
  },
  {
    id: 79,
    word: "sere",
    phonetic: "sere",
    partOfSpeech: "noun / verb",
    fijianDef: "Ko sere e vakayacori taka na vosa ka na nakiti — na veivakatauyavutaki ni sere vakaviti. E dau vakayacori na sere ni meke, na sere ni lotu, ka na sere ni marau.",
    englishDef: "Song; to sing. Music and song are central to Fijian cultural expression, from church hymns to meke performances.",
    example: "Me ra sere na gone!",
    exampleTranslation: "Let the children sing!",
    category: "culture",
    tags: ["cultural", "arts"]
  },
  {
    id: 80,
    word: "vuli",
    phonetic: "vuli",
    partOfSpeech: "verb / noun",
    fijianDef: "Ko vuli e vakayacori taka na cakacaka ni kaukauwa — na vakakaukauwa ni tamata. E dau vakayacori ki na kena tacivaki na nodra vuli na gone.",
    englishDef: "To learn; to study; education. The process of acquiring knowledge. Education is highly valued in Fiji.",
    example: "Na gone e dau vuli vinaka.",
    exampleTranslation: "The child studies well.",
    category: "society",
    tags: ["education", "everyday"]
  },
  {
    id: 81,
    word: "veivuke",
    phonetic: "veivuke",
    partOfSpeech: "noun / verb",
    fijianDef: "Ko veivuke e vakayacori taka na veivakaitavi — na veivosaki ni veivuke. E vakayacori na loloma ka na veiqaravi.",
    englishDef: "Help; assistance; to help. The act of helping someone. Community cooperation and mutual aid (veivuke) is a cornerstone of Fijian village life.",
    example: "Vinaka na nomu veivuke.",
    exampleTranslation: "Thank you for your help.",
    category: "society",
    tags: ["everyday", "social"]
  },
  {
    id: 82,
    word: "cakacaka",
    phonetic: "thakathaka",
    partOfSpeech: "noun / verb",
    fijianDef: "Ko cakacaka e vakayacori taka na ka e cakava na tamata — na gausa ni bula. E dau vakayacori 'cakacaka vinaka' (work well).",
    englishDef: "Work; job; to work. The act of working. Also refers to how something functions — 'e cakacaka vinaka' means 'it works well'.",
    example: "Au sa cakacaka nikua.",
    exampleTranslation: "I am working today.",
    category: "verbs",
    tags: ["everyday"]
  },
  {
    id: 83,
    word: "taura",
    phonetic: "taura",
    partOfSpeech: "verb",
    fijianDef: "Ko taura e vakayacori taka na veivesu — na veivakaurui mai na ka. E dau vakayacori 'taura na yaqona' (take the kava).",
    englishDef: "To take; to hold; to receive. The act of taking or holding something. Also used when receiving gifts or offerings.",
    example: "Taura mai na bilo.",
    exampleTranslation: "Take the cup.",
    category: "verbs",
    tags: ["everyday"]
  },
  {
    id: 84,
    word: "soli",
    phonetic: "soli",
    partOfSpeech: "verb",
    fijianDef: "Ko soli e vakayacori taka na veisoli — na veivakaitavi ni ka ki na tamata tale. E dau vakayacori 'soli vata' (give together), na veisoli ni yaqona.",
    englishDef: "To give; to offer. One of the most important actions in Fijian culture. Generosity in giving is a mark of good character.",
    example: "Soli mai na ika.",
    exampleTranslation: "Give me some fish.",
    category: "verbs",
    tags: ["everyday", "cultural"]
  },
  {
    id: 85,
    word: "vakavinaka",
    phonetic: "vakavinaka",
    partOfSpeech: "verb / adjective",
    fijianDef: "Ko vakavinaka e vakayacori taka na veivakatauyavutaki ni vinaka — na kena vakatauyavutaki na vinaka. E dau vakayacori 'vakavinaka sara' (make it very good).",
    englishDef: "To improve; to make good; well (behaved). Derived from 'vinaka', used to describe improving something or someone's good behavior.",
    example: "Me vakavinaka na nomu cakacaka.",
    exampleTranslation: "Make your work good.",
    category: "descriptive",
    tags: ["everyday"]
  },
  {
    id: 86,
    word: "bibi",
    phonetic: "mimbi",
    partOfSpeech: "adjective",
    fijianDef: "Ko bibi e vakayacori taka na ka e bibi — na kena bibi. E dau vakayacori ki na ka bibi ka na veivosaki bibi.",
    englishDef: "Heavy; serious; important. Describes something with weight, either physical or metaphorical. 'Veivosaki bibi' = serious conversation.",
    example: "Na tabua e bibi.",
    exampleTranslation: "The whale tooth is heavy/serious.",
    category: "descriptive",
    tags: ["everyday"]
  },
  {
    id: 87,
    word: "leka",
    phonetic: "leka",
    partOfSpeech: "adjective",
    fijianDef: "Ko leka e vakayacori taka na ka e lailai na kena leka — e leqa cake mai na 'balavu'. E dau vakayacori ki na tamata se ka e leka.",
    englishDef: "Short; brief. The opposite of 'balavu' (long/tall). Describes height or length.",
    example: "Na taci e leka.",
    exampleTranslation: "The younger sibling is short.",
    category: "descriptive",
    tags: ["everyday"]
  },
  {
    id: 88,
    word: "balavu",
    phonetic: "mbalavu",
    partOfSpeech: "adjective",
    fijianDef: "Ko balavu e vakayacori taka na ka e balavu — e leqa cake mai na 'leka'. E dau vakayacori ki na tamata, ki na ika, ka na vanua.",
    englishDef: "Long; tall. Describes height or length. The opposite of 'leka'.",
    example: "Na tamana e balavu.",
    exampleTranslation: "The father is tall.",
    category: "descriptive",
    tags: ["everyday"]
  },
  {
    id: 89,
    word: "cici",
    phonetic: "thithi",
    partOfSpeech: "verb",
    fijianDef: "Ko cici e vakayacori taka na cakacaka ni cici — na tosoi rawarawa. E dau vakayacori ki na gone e ra cici, ki na wai e cici, ka na siga e cici.",
    englishDef: "To run; to flow (for water). Children cici across the rara; rivers cici to the sea.",
    example: "Na gone e dau cici.",
    exampleTranslation: "The child often runs.",
    category: "verbs",
    tags: ["everyday"]
  },
  {
    id: 90,
    word: "rere",
    phonetic: "rere",
    partOfSpeech: "verb / adjective",
    fijianDef: "Ko rere e vakayacori taka na loma e oca — na veivakavuidravi. E dau vakayacori 'au rere' (I am afraid).",
    englishDef: "To fear; afraid; frightened. Describes a state of fear or alarm.",
    example: "Au sa rere ni bogi.",
    exampleTranslation: "I am afraid of the night.",
    category: "emotions",
    tags: ["emotions"]
  },
  {
    id: 91,
    word: "lomana",
    phonetic: "lomana",
    partOfSpeech: "verb",
    fijianDef: "Ko lomana e vakayacori taka na loloma ki na ka se tamata — na veivakatauyavutaki ni loloma. E kaya 'to love someone/something'.",
    englishDef: "To love (someone/something). The transitive form of 'loloma'. 'Au lomana iko' = 'I love you'.",
    example: "Au lomana iko.",
    exampleTranslation: "I love you.",
    category: "emotions",
    tags: ["essential", "emotions"]
  },
  {
    id: 92,
    word: "kaukauwa",
    phonetic: "kaukauwa",
    partOfSpeech: "adjective / noun",
    fijianDef: "Ko kaukauwa e vakayacori taka na ka e kaukauwa — na ivakatagedegede ni kaukauwa. E leqa cake mai na 'valevale'.",
    englishDef: "Strong; strength. Describes physical or moral strength. Used to compliment warriors, hardworking people, or describe robust things.",
    example: "E kaukauwa na noda matanitu.",
    exampleTranslation: "Our nation is strong.",
    category: "descriptive",
    tags: ["everyday"]
  },
  {
    id: 93,
    word: "vakatakilakila",
    phonetic: "vakatakilakila",
    partOfSpeech: "verb",
    fijianDef: "Ko vakatakilakila e vakayacori taka na veivakatauyavutaki ni ka — na vosa ni vakarokoroko. E dau vakayacori ki na veivosaki ni turaga.",
    englishDef: "To show; to demonstrate; to present formally. The act of presenting something important or introducing with ceremony.",
    example: "Me vakatakilakila na turaga.",
    exampleTranslation: "Introduce/present the chief.",
    category: "verbs",
    tags: ["formal", "cultural"]
  },
  {
    id: 94,
    word: "dina",
    phonetic: "ndina",
    partOfSpeech: "adjective / adverb",
    fijianDef: "Ko dina e vakayacori taka na veidinadinataki — na ka e dina. E dau vakayacori 'e dina' (it is true), 'dina sara' (truly).",
    englishDef: "True; real; indeed. Used to affirm truth or reality. 'E dina' = 'it is true'. 'Dina sara' = 'truly indeed'.",
    example: "E dina, au lomana iko.",
    exampleTranslation: "Truly, I love you.",
    category: "basics",
    tags: ["everyday"]
  },
  {
    id: 95,
    word: "tekivu",
    phonetic: "tekivu",
    partOfSpeech: "verb",
    fijianDef: "Ko tekivu e vakayacori taka na veitekivu — na yabaki mai na ka. E dau vakayacori 'me tekivu' (let it begin).",
    englishDef: "To begin; to start. The action of starting something.",
    example: "Me tekivu na meke!",
    exampleTranslation: "Let the dance begin!",
    category: "verbs",
    tags: ["everyday"]
  },
  {
    id: 96,
    word: "oca",
    phonetic: "otha",
    partOfSpeech: "verb / adjective",
    fijianDef: "Ko oca e vakayacori taka na ka e oca — na ka e dredre ni cakava. E dau vakayacori 'au sa oca' (I am tired).",
    englishDef: "Tired; exhausted; to be tired. Describes fatigue from work or effort.",
    example: "Au sa oca vakalevu.",
    exampleTranslation: "I am very tired.",
    category: "emotions",
    tags: ["everyday"]
  },
  {
    id: 97,
    word: "waqa",
    phonetic: "wangga",
    partOfSpeech: "noun",
    fijianDef: "Ko waqa e vakayacori taka na waqa ni wasa — na ivakarau ni vakalako ki na wai. E dau vakayacori ki na waqawaqa vakalevu ka na waqa lailai.",
    englishDef: "Boat; canoe; ship. Any vessel that travels on water. The traditional Fijian double-hulled canoe (drua) was once the mightiest craft in the Pacific.",
    example: "Na waqa e lako ki na yanuyanu.",
    exampleTranslation: "The boat goes to the island.",
    category: "nature",
    tags: ["everyday", "cultural"]
  },
  {
    id: 98,
    word: "yanuyanu",
    phonetic: "yanyanu",
    partOfSpeech: "noun",
    fijianDef: "Ko yanuyanu e vakayacori taka na vanua e tiko e loma ni wasa — na ivakarau ni vanua ni Viti. Ko Viti e tiko na yanuyanu e 330.",
    englishDef: "Island. Fiji is an archipelago of over 330 islands — yanuyanu is central to Fijian identity.",
    example: "Ko Viti e vanua ni yanuyanu vinaka.",
    exampleTranslation: "Fiji is a land of beautiful islands.",
    category: "nature",
    tags: ["everyday", "cultural"]
  },
  {
    id: 99,
    word: "wasa",
    phonetic: "wasa",
    partOfSpeech: "noun",
    fijianDef: "Ko wasa e vakayacori taka na wai levu — na rara ni ika. E dau vakayacori 'wasa levu' (ocean) ka 'wasa lailai' (lagoon/sea).",
    englishDef: "Sea; ocean; open water. The surrounding ocean is essential to Fijian life, culture, and economy.",
    example: "Na wasa e bibi ki Viti.",
    exampleTranslation: "The sea is important to Fiji.",
    category: "nature",
    tags: ["nature", "everyday"]
  },
  {
    id: 100,
    word: "kaukauwa ni loloma",
    phonetic: "kaukauwa ni loloma",
    partOfSpeech: "phrase",
    fijianDef: "Ko kaukauwa ni loloma e vakayacori taka na kaukauwa e mai na loloma — na kaukauwa ni noda veiwekani.",
    englishDef: "The strength of love. A Fijian philosophical phrase — true strength comes from love and compassion, not force.",
    example: "Na kaukauwa ni loloma e sivia na cakacaka.",
    exampleTranslation: "The strength of love surpasses all work.",
    category: "phrases",
    tags: ["cultural", "wisdom"]
  },
  {
    id: 101,
    word: "dauveilewai",
    phonetic: "ndauveilewai",
    partOfSpeech: "noun",
    fijianDef: "Ko dauveilewai e vakayacori taka na tamata e dau veivosaki na lewai — na tamata e turaga na kena vakavinavinakataki.",
    englishDef: "Peacemaker; one who reconciles disputes. A highly respected role in Fijian society — someone who helps resolve conflict through talanoa.",
    category: "society",
    tags: ["cultural", "society"]
  },
  {
    id: 102,
    word: "tamata",
    phonetic: "tamata",
    partOfSpeech: "noun",
    fijianDef: "Ko tamata e vakayacori taka na ira na ivakatagedegede ni tamata — na ira na tamata levu. E dau vakayacori ki na matavuvale ka na veivosaki.",
    englishDef: "Person; human being; people. The general word for a person or people. Central to Fijian worldview — people are the most important part of life.",
    example: "Ko koya e tamata vinaka.",
    exampleTranslation: "He/she is a good person.",
    category: "people",
    tags: ["everyday", "essential"]
  },
  {
    id: 103,
    word: "vakacegu",
    phonetic: "vakathenggu",
    partOfSpeech: "verb / noun",
    fijianDef: "Ko vakacegu e vakayacori taka na vakatauyavutaki ni cegu — na veimocetaki. E dau vakayacori 'vakacegu ga' (just rest).",
    englishDef: "To rest; to relax; rest time. The act of taking a break or resting. 'Vakacegu ga' — just relax — captures the Fijian spirit of unhurried living.",
    example: "Me vakacegu na tamata.",
    exampleTranslation: "Let the person rest.",
    category: "verbs",
    tags: ["everyday", "cultural"]
  },
  {
    id: 104,
    word: "vinakataka",
    phonetic: "vinakataka",
    partOfSpeech: "verb",
    fijianDef: "Ko vinakataka e vakayacori taka na veivakatauyavutaki ni vinaka ki na ka tale — na vakavinavinakataki.",
    englishDef: "To appreciate; to be grateful for. The act of expressing gratitude toward something specific.",
    example: "Au vinakataka na nomu loloma.",
    exampleTranslation: "I appreciate your love.",
    category: "emotions",
    tags: ["everyday"]
  },
  {
    id: 105,
    word: "cauravou",
    phonetic: "thauravou",
    partOfSpeech: "noun",
    fijianDef: "Ko cauravou e vakayacori taka na gone tagane e levu cake — na tamata tagane e saqara tu na nona ivola. E dau vakayacori ki na vaqara ni turaga.",
    englishDef: "Young man; youth. A young man of working/warrior age. Cauravou have important roles in village ceremonies and helping elders.",
    example: "Na cauravou e cakacaka vinaka.",
    exampleTranslation: "The young man works well.",
    category: "people",
    tags: ["people", "cultural"]
  }
,
  // ── EXPANSION PACK: Tourism, Travel & Places (106–135) ────────────────
  {
    id: 106,
    word: "Nadi",
    phonetic: "Nandi",
    partOfSpeech: "proper noun",
    fijianDef: "Ko Nadi e dua na koro levu e Viti Levu — na vanua e tiko kina na waqa ni yaloyalo levu duadua e Viti. E na nona veisiga e ra mai yaco kina na vulagi mai na matanitu vuravura vaka taucoko.",
    englishDef: "Nadi — the main tourist hub on Viti Levu and home to Nadi International Airport, Fiji's primary gateway. Nadi is where most visitors to Fiji begin their journey.",
    example: "Au lako mai Nadi me yaco ki Suva.",
    exampleTranslation: "I travelled from Nadi to Suva.",
    category: "travel",
    tags: ["place", "tourism", "essential"]
  },
  {
    id: 107,
    word: "Denarau",
    phonetic: "Ndendrau",
    partOfSpeech: "proper noun",
    fijianDef: "Ko Denarau e dua na yanuyanu lailai e rarama — na vanua e tiko kina na vale ni vulagi vinaka ka na waqa ni tiko e Viti. Na Port Denarau e dua na matai ni waqa e rokomoka.",
    englishDef: "Denarau Island — a world-class resort destination near Nadi, home to Port Denarau Marina, luxury hotels, and the departure point for island cruises. A hub for Fiji Tours & Transfers guests.",
    example: "Na port e tiko i Denarau.",
    exampleTranslation: "The port is located at Denarau.",
    category: "travel",
    tags: ["place", "tourism"]
  },
  {
    id: 108,
    word: "Sigatoka",
    phonetic: "Singatoka",
    partOfSpeech: "proper noun",
    fijianDef: "Ko Sigatoka e dua na koro e Viti Levu — na vanua e tiko kina na cawa vinaka ka na ivi ni yaqona e rokomoka. E vakarau kina na rara ni Sigatoka River.",
    englishDef: "Sigatoka — a town on the Coral Coast famous for the Sigatoka River, Biausevu Waterfall hikes, and the Sigatoka Sand Dunes. A top destination for Coral Coast tours.",
    example: "E vinaka na ciqomi i Sigatoka.",
    exampleTranslation: "The sightseeing in Sigatoka is wonderful.",
    category: "travel",
    tags: ["place", "tourism"]
  },
  {
    id: 109,
    word: "Natadola",
    phonetic: "Natandola",
    partOfSpeech: "proper noun",
    fijianDef: "Ko Natadola e dua na baravi e rokomoka e Viti Levu — na baravi e vinaka duadua e Viti. E tiko kina na hosi e dau vakaririko ka na coka ni baravi e loaloa.",
    englishDef: "Natadola Beach — consistently rated one of Fiji's most beautiful beaches, famed for horse riding along the shore and crystal-clear water. Featured on the Coral Coast horse riding tours.",
    example: "Na baravi i Natadola e loaloa vinaka.",
    exampleTranslation: "The beach at Natadola is very clear and beautiful.",
    category: "travel",
    tags: ["place", "tourism"]
  },
  {
    id: 110,
    word: "Savusavu",
    phonetic: "Savusavu",
    partOfSpeech: "proper noun",
    fijianDef: "Ko Savusavu e dua na koro e Vanua Levu — na yanuyanu e lua levu e Viti. E rokomoka na kena waiwai voleka ka na kena baravi loaloa. E dau kacivi ko ia na \"hidden paradise\" ni Viti.",
    englishDef: "Savusavu — a charming harbour town on Vanua Levu, Fiji's second-largest island, known for its hot springs, pristine beaches, and yacht marina. Served by Fiji Tours & Transfers airport connections.",
    example: "Ko Savusavu e tiko e Vanua Levu.",
    exampleTranslation: "Savusavu is located on Vanua Levu.",
    category: "travel",
    tags: ["place", "tourism"]
  },
  {
    id: 111,
    word: "Biausevu",
    phonetic: "Mbiausevu",
    partOfSpeech: "proper noun",
    fijianDef: "Ko Biausevu e dua na koro vakavanua e Sigatoka — na vanua e tiko kina na uciwai e rokomoka. Na koro oqo e dau bilivilidata na vulagi me rawa ni raici na uciwai.",
    englishDef: "Biausevu — a traditional Fijian village near Sigatoka where visitors hike to the famous Biausevu Waterfall. A highlight of the Sigatoka hiking and waterfall tour experience.",
    example: "Me lako ki Biausevu me raica na uciwai.",
    exampleTranslation: "Go to Biausevu to see the waterfall.",
    category: "travel",
    tags: ["place", "tourism"]
  },
  {
    id: 112,
    word: "Lautoka",
    phonetic: "Lautoka",
    partOfSpeech: "proper noun",
    fijianDef: "Ko Lautoka e koro e lua levu e Viti — na \"Sugar City\" ni Viti. E tiko e ðelagi e Viti Levu. Na kena waqa ni yaloyalo e dau sivia na waqa ni cruise.",
    englishDef: "Lautoka — Fiji's second city and main sugar-producing town, known as the Sugar City. Its deep-water port is a major stop for cruise ships visiting Fiji.",
    example: "Na Sugar City ko Lautoka.",
    exampleTranslation: "Lautoka is the Sugar City.",
    category: "travel",
    tags: ["place", "tourism"]
  },
  {
    id: 113,
    word: "Nausori",
    phonetic: "Nausori",
    partOfSpeech: "proper noun",
    fijianDef: "Ko Nausori e dua na koro e voleka ko Suva — na koro e tiko kina na waqa ni yaloyalo ni Suva. E na nona veisiga e ra cakacaka kina na lewe ni vanua e vuqa.",
    englishDef: "Nausori — a town near Suva and home to Nausori Airport. The operations base of Fiji Tours & Transfers, staffed by local Fijian guides with deep knowledge of the island.",
    example: "Ko Nausori e voleka ko Suva.",
    exampleTranslation: "Nausori is close to Suva.",
    category: "travel",
    tags: ["place", "tourism"]
  },
  {
    id: 114,
    word: "Viti Levu",
    phonetic: "Viti Levu",
    partOfSpeech: "proper noun",
    fijianDef: "Ko Viti Levu e na yanuyanu levu duadua e Viti — na vanua e tiko kina na koro levu ko Suva ka na koro bibi ko Nadi. E vuqa na vulagi e sivia e curu mai e na yanuyanu oqo.",
    englishDef: "Viti Levu — the main island of Fiji and home to most of the country's population, major towns, and tourist destinations including Nadi, Suva, Sigatoka, and the Coral Coast.",
    example: "Na koro levu e Viti Levu ko Suva.",
    exampleTranslation: "The capital of Viti Levu is Suva.",
    category: "travel",
    tags: ["place", "essential"]
  },
  {
    id: 115,
    word: "uciwai",
    phonetic: "uthiwai",
    partOfSpeech: "noun",
    fijianDef: "Ko uciwai e vakayacori taka na wai e uci sara mai na vatu — dua na ka vinaka e dau raici na vulagi e Viti. Na uciwai i Biausevu e rokomoka sara.",
    englishDef: "Waterfall. A natural waterfall — one of Fiji's most spectacular natural features. The Biausevu Waterfall near Sigatoka is a famous guided hiking destination.",
    example: "E totoka na uciwai i Biausevu.",
    exampleTranslation: "The Biausevu waterfall is beautiful.",
    category: "nature",
    tags: ["nature", "tourism"]
  },
  {
    id: 116,
    word: "waqa ni yaloyalo",
    phonetic: "wanga ni yaloyalo",
    partOfSpeech: "noun phrase",
    fijianDef: "Ko waqa ni yaloyalo e vakayacori taka na waqa levu e dau cakacaka e lagi — na mona ni lako yaloyalo. E dau veisautaka na tamata mai na matanitu e dua ki na matanitu e dua tale.",
    englishDef: "Aeroplane; aircraft. The primary way most visitors arrive in Fiji, landing at Nadi International Airport before beginning their island adventures with a transfer service.",
    example: "Au lako mai e na waqa ni yaloyalo.",
    exampleTranslation: "I came by aeroplane.",
    category: "travel",
    tags: ["travel", "tourism"]
  },
  {
    id: 117,
    word: "lako",
    phonetic: "lako",
    partOfSpeech: "verb",
    fijianDef: "Ko lako e vakayacori taka na cakacaka ni ðede — na lako mai, lako tani, ka na veivosaki ni leqa. E dau vakayacori tu ga na vosa oqo e na veivosaki ni siga taucoko.",
    englishDef: "To go; to travel; to move. The most common Fijian verb for movement and travel. 'Me lako' — let's go — is heard constantly on tours and transfers across the islands.",
    example: "Me lako tani!",
    exampleTranslation: "Let's go!",
    category: "verbs",
    tags: ["essential", "travel"]
  },
  {
    id: 118,
    word: "ciqomi",
    phonetic: "thingomi",
    partOfSpeech: "verb",
    fijianDef: "Ko ciqomi e vakayacori taka na bilivilidata ni vanua — na kena raici ka na kena lomani. E dau kacivi ko Viti na vulagi me ra ciqomi na totoka ni vanua.",
    englishDef: "To sightsee; to explore and appreciate a place. Sightseeing (ciqomi) is the heart of every Fiji tour — exploring waterfalls, villages, beaches, and highlands with local guides.",
    example: "Au via ciqomi na vanua ðe.",
    exampleTranslation: "I want to sightsee this place.",
    category: "travel",
    tags: ["travel", "tourism"]
  },
  {
    id: 119,
    word: "veitarogi",
    phonetic: "veitarogi",
    partOfSpeech: "noun / verb",
    fijianDef: "Ko veitarogi e vakayacori taka na veivosaki ni se mai yaco — na veirogorogoci ni tamata e kua ni se kilai. E dau bilivilidata tu na vulagi mai Nadi e na veitarogi vakayaco.",
    englishDef: "Introduction; welcoming greeting. The warm, culturally rich welcome given to visitors arriving in Fiji — from airport transfers to village ceremonies, the veitarogi sets the tone for the whole experience.",
    example: "Na veitarogi e vinaka vakalevu.",
    exampleTranslation: "The welcome was very wonderful.",
    category: "greetings",
    tags: ["cultural", "tourism"]
  },
  {
    id: 120,
    word: "dua tale",
    phonetic: "ndua tale",
    partOfSpeech: "phrase",
    fijianDef: "Ko dua tale e vakayacori taka na veivosaki ni veisautaki — na dua na ka tale, dua na gauna tale. E dau vakayacori na vosa oqo me vakaraitaka na lomalomai ni soli tale.",
    englishDef: "One more; again; another one. A phrase of enthusiasm — often heard from happy visitors asking for one more experience, one more day, one more adventure in the islands of Fiji.",
    example: "Au via lako dua tale!",
    exampleTranslation: "I want to go again!",
    category: "phrases",
    tags: ["everyday", "tourism"]
  },
  {
    id: 121,
    word: "hosi",
    phonetic: "hosi",
    partOfSpeech: "noun",
    fijianDef: "Ko hosi e vakayacori taka na manumanu levu e dau veiqaravi na tamata — na manumanu e dau vakayacori ki na lako e vanua. E rokomoka i Natadola na veivakaririko hosi e na baravi.",
    englishDef: "Horse. Horses are a famous attraction at Natadola Beach and the Coral Coast, where visitors can ride along the shoreline on guided horse tours — one of Fiji's most memorable experiences.",
    example: "Au vakaririko hosi e na baravi.",
    exampleTranslation: "I rode a horse on the beach.",
    category: "nature",
    tags: ["tourism", "animals"]
  },
  {
    id: 122,
    word: "vulagi",
    phonetic: "vulagi",
    partOfSpeech: "noun",
    fijianDef: "Ko vulagi e vakayacori taka na tamata e mai talei mai na vanua tale — na dauveitaura. E na nona veisiga e ra marau sara na lewe ni vanua me ra bilivilidata na vulagi ka ra vakavinavinakata na nodra mai yaco.",
    englishDef: "Visitor; tourist; guest. In Fijian culture, guests are treated with extraordinary warmth and generosity. Every vulagi arriving through Nadi Airport is welcomed as family — the Fiji way.",
    example: "Na vulagi e bilivilidata me ra kana.",
    exampleTranslation: "The guests were invited to eat.",
    category: "people",
    tags: ["tourism", "cultural"]
  },
  {
    id: 123,
    word: "baravi",
    phonetic: "mbaravi",
    partOfSpeech: "noun",
    fijianDef: "Ko baravi e vakayacori taka na sova ni vanua e voleka na waitui — na vanua e dau veisigani ka veicegumi kina na tamata. Na baravi i Natadola e rokomoka e vuqa na matanitu.",
    englishDef: "Beach; shoreline. Fiji's beaches are world-famous — from the crystal sands of Natadola to the sheltered coves of the Coral Coast. Every beach experience is better with a local guide.",
    example: "Na baravi e loaloa ka totoka.",
    exampleTranslation: "The beach is clear and beautiful.",
    category: "nature",
    tags: ["nature", "tourism", "essential"]
  },
  {
    id: 124,
    word: "waitui",
    phonetic: "waitui",
    partOfSpeech: "noun",
    fijianDef: "Ko waitui e vakayacori taka na wai levu e dau sivia na siga — na waitui. E tiko na vanua ko Viti e na lotoloto ni waitui kina e ra siga voleka na siga taucoko.",
    englishDef: "Ocean; sea. The Pacific Ocean surrounds Fiji's 300+ islands, defining the island lifestyle. Fiji's seas offer world-class diving, snorkelling, sailing, and island-hopping adventures.",
    example: "Na waitui e loaloa e Viti.",
    exampleTranslation: "The ocean is crystal clear in Fiji.",
    category: "nature",
    tags: ["nature", "essential"]
  },
  {
    id: 125,
    word: "yanuyanu",
    phonetic: "yanunyanu",
    partOfSpeech: "noun",
    fijianDef: "Ko yanuyanu e vakayacori taka na vanua e sivia na waitui e tuvata kina. Ko Viti e vuqa na kena yanuyanu — e 330 na yanuyanu e volekati na lewe ni vanua.",
    englishDef: "Island. Fiji is an archipelago of over 330 islands, each with its own character — from the bustling main island of Viti Levu to remote palm-fringed islets accessible by boat tour.",
    example: "Na yanuyanu i Viti e totoka sara.",
    exampleTranslation: "The islands of Fiji are incredibly beautiful.",
    category: "nature",
    tags: ["nature", "essential", "tourism"]
  },
  {
    id: 126,
    word: "koro",
    phonetic: "koro",
    partOfSpeech: "noun",
    fijianDef: "Ko koro e vakayacori taka na vanua e bula kina na lewe ni vanua vakamatatuvaki — na koro ni Viti. Na koro e vakabibi na bula vakavanua ka na veiqaravi ni tamata.",
    englishDef: "Village; town. Traditional Fijian villages are the heart of local culture — visitors on guided tours often stop at villages to experience ceremonies, kava rituals, and genuine Fijian hospitality.",
    example: "Au ra bilivilidata e na koro.",
    exampleTranslation: "I was welcomed in the village.",
    category: "places",
    tags: ["cultural", "tourism"]
  },
  {
    id: 127,
    word: "veisiga",
    phonetic: "veisiga",
    partOfSpeech: "noun",
    fijianDef: "Ko veisiga e vakayacori taka na vakayacori ni siga kina na tamata e cakacaka kina. Na \"veisiga ni vulagi\" e dau vakayacori na loma ni siga ni vulagi e bula kina e Viti.",
    englishDef: "Holiday; vacation; time of leisure. 'Veisiga' captures the spirit of a Fiji holiday — unhurried days, warm welcomes, stunning scenery, and unforgettable tours with local experts.",
    example: "Na noqu veisiga e vinaka sara!",
    exampleTranslation: "My holiday was absolutely wonderful!",
    category: "travel",
    tags: ["travel", "tourism"]
  },
  {
    id: 128,
    word: "Coral Coast",
    phonetic: "Coral Coast",
    partOfSpeech: "proper noun",
    fijianDef: "Ko Coral Coast e dua na vanua e rokomoka e sova ni wasawasa ni Viti Levu — na vanua e tiko kina na barrivi ka na ika ni katou. E vuqa na vale ni vulagi ka na vanua ni lako i kea.",
    englishDef: "Coral Coast — a stunning stretch of Viti Levu's south coast known for its coral reefs, resorts, and horse riding tours. One of the most popular destinations served by Fiji Tours & Transfers.",
    example: "Na Coral Coast e vinaka vakalevu.",
    exampleTranslation: "The Coral Coast is very beautiful.",
    category: "travel",
    tags: ["place", "tourism"]
  },
  {
    id: 129,
    word: "gone ni lako",
    phonetic: "ngone ni lako",
    partOfSpeech: "noun phrase",
    fijianDef: "Ko gone ni lako e vakayacori taka na gone e lako kina e na veivakacalai — na \"tour guide\". Na gone ni lako e vakabibi na lako mai na gauna ni veisiga.",
    englishDef: "Tour guide. A local guide who leads visitors through Fiji's landscapes, villages, and attractions. Fiji Tours & Transfers prides itself on licensed, knowledgeable local guides who bring destinations to life.",
    example: "Na gone ni lako e kilai vinaka na vanua.",
    exampleTranslation: "The tour guide knows the land well.",
    category: "travel",
    tags: ["tourism", "people"]
  },
  {
    id: 130,
    word: "veivakacalai",
    phonetic: "veivakathali",
    partOfSpeech: "noun",
    fijianDef: "Ko veivakacalai e vakayacori taka na veisigani kina na ka ni ciqomi — na \"tour\". E na nona veisiga e ra vuqa na vulagi e ra solia na nodra ilavo me ra ciqomi na vanua vakaveitikina.",
    englishDef: "Tour; guided excursion. A structured tour of Fiji's attractions — from waterfall hikes and river cruises to zip-lining and cultural night experiences. The foundation of the island holiday industry.",
    example: "Na veivakacalai e vinaka sara.",
    exampleTranslation: "The tour was absolutely wonderful.",
    category: "travel",
    tags: ["tourism", "essential"]
  },
  // ── EXPANSION PACK: Culture, Ceremony & Society (131–145) ─────────────
  {
    id: 131,
    word: "sevusevu",
    phonetic: "sevusevu",
    partOfSpeech: "noun / ceremony",
    fijianDef: "Ko sevusevu e dua na veiqaravi vakavanua — na soli ni yaqona ki na turaga ni koro me rawa ni curu kina na tamata. E dodonu me caka taumada na sevusevu me yaco ki na koro.",
    englishDef: "A traditional Fijian welcoming ceremony involving the presentation of yaqona (kava) to village elders. Every visitor entering a village must perform sevusevu — it is the foundation of Fijian hospitality.",
    example: "E dodonu me caka na sevusevu taumada.",
    exampleTranslation: "The welcoming ceremony must be done first.",
    category: "culture",
    tags: ["cultural", "ceremony", "essential"]
  },
  {
    id: 132,
    word: "meke",
    phonetic: "meke",
    partOfSpeech: "noun",
    fijianDef: "Ko meke e dua na veiqaravi ni vuqa ka ni sere — na itikotiko ni nodratou veivosaki na lewe ni vanua. E dau caka na meke e na veiqaravi ni siga bibi ka na vakamarautaki ni vulagi.",
    englishDef: "Traditional Fijian dance and song performance. Meke is performed at cultural ceremonies, festivals, and tourist cultural nights — a vibrant display of story, history, and community through movement.",
    example: "Na meke e totoka ka e dau marautaki.",
    exampleTranslation: "The traditional dance is beautiful and joyful.",
    category: "culture",
    tags: ["cultural", "ceremony"]
  },
  {
    id: 133,
    word: "lovo",
    phonetic: "lovo",
    partOfSpeech: "noun",
    fijianDef: "Ko lovo e dau vakayacori taka na vuata ni kana e dau taucaka e na vunikau — na kena taucaka e na loma ni magimagi ka vatu. E dau cakava na lewe ni koro e na veiqaravi ni siga bibi.",
    englishDef: "Earth oven; a traditional Fijian feast cooked underground using hot stones. Lovo feasts are a highlight of cultural tours and village visits — meats, fish, and root vegetables slow-cooked to perfection.",
    example: "Na kana i lovo e totoka sara.",
    exampleTranslation: "The earth oven food is absolutely delicious.",
    category: "food",
    tags: ["cultural", "food", "ceremony"]
  },
  {
    id: 134,
    word: "sulu",
    phonetic: "sulu",
    partOfSpeech: "noun",
    fijianDef: "Ko sulu e dua na isulu e dau vakataraisautaka na lewe ni vanua — na isulu ni tagane ka ni yalewa e Viti. E dodonu me cakava na tamata na sulu me curu ki na koro ka na vale ni lotu.",
    englishDef: "A traditional wrap garment worn by Fijians, similar to a sarong. Visitors to Fijian villages must wear a sulu as a sign of respect — tour guides ensure guests are culturally prepared before village stops.",
    example: "E dodonu me cakava na sulu me curu ki na koro.",
    exampleTranslation: "You must wear a sulu to enter the village.",
    category: "culture",
    tags: ["cultural", "clothing"]
  },
  {
    id: 135,
    word: "talanoa",
    phonetic: "talanoa",
    partOfSpeech: "noun / verb",
    fijianDef: "Ko talanoa e vakayacori taka na veivosaki totoka — na veivosaki ni loloma ka na vakavinavinakataki. E vakabibi na talanoa e na bula vakavanua ni Viti — na veivosaki totoka e vakatautauvata na lewe ni vanua.",
    englishDef: "Meaningful conversation; storytelling; open dialogue. Talanoa is the Fijian tradition of sitting together and talking openly — practiced on river cruises, village stays, and cultural evenings across Fiji.",
    example: "Me tiko na talanoa vinaka!",
    exampleTranslation: "Let there be good conversation!",
    category: "culture",
    tags: ["cultural", "essential"]
  },
  {
    id: 136,
    word: "masi",
    phonetic: "masi",
    partOfSpeech: "noun",
    fijianDef: "Ko masi e dua na ka ni cakacaka e cakava na lewe ni vanua — na kena caka e na korokoro ni vu ni vunikau e kacivi na \"paper mulberry\". Na masi e dau leqa ca na veiqaravi ka na isulu ni veiqaravi.",
    englishDef: "Tapa cloth; traditional barkcloth made from the paper mulberry tree. Masi is decorated with intricate geometric patterns unique to each clan and is given as a ceremonial gift — prized by cultural tour visitors.",
    example: "Na masi e vakayacori taka na ivakarau ni lewe ni vanua.",
    exampleTranslation: "Tapa cloth represents the culture of the people.",
    category: "culture",
    tags: ["cultural", "crafts"]
  },
  {
    id: 137,
    word: "tabua",
    phonetic: "tambua",
    partOfSpeech: "noun",
    fijianDef: "Ko tabua e dua na ivakarau bibi e Viti — na nifo ni toa ni waitui. E dau solia na tabua e na veiqaravi bibi — na veivakamareqeti, na veiwekani, ka na veitauri ni nodra veiliutaki.",
    englishDef: "Whale's tooth — the most sacred and valuable ceremonial object in Fijian culture. Tabua are presented at births, deaths, marriages, and important negotiations. Seeing a tabua ceremony on a cultural tour is unforgettable.",
    example: "Na tabua e ka bibi sara e na bula vakavanua.",
    exampleTranslation: "The whale's tooth is very important in cultural life.",
    category: "culture",
    tags: ["cultural", "ceremony"]
  },
  {
    id: 138,
    word: "vakavanua",
    phonetic: "vakavanua",
    partOfSpeech: "adverb / adjective",
    fijianDef: "Ko vakavanua e vakayacori taka na ka e caka vakaitikotiko — \"in the Fijian way\". E dau vakayacori me vakaraica na ka e caka vakamataivalu ni Viti.",
    englishDef: "In the traditional way; according to Fijian custom. 'Vakavanua' describes doing things the authentic Fijian way — from preparing yaqona to greeting visitors and conducting ceremonies on cultural tours.",
    example: "E caka vakavanua na sevusevu.",
    exampleTranslation: "The welcome ceremony is done in the traditional way.",
    category: "culture",
    tags: ["cultural", "essential"]
  },
  {
    id: 139,
    word: "waqawaqa",
    phonetic: "wangawanga",
    partOfSpeech: "noun",
    fijianDef: "Ko waqawaqa e vakayacori taka na cakacaka ni waqa e na waitui — na lako e na waqa i waiwai. E dau vakayacori na waqawaqa e na veiqaravi ni vulagi e ra lako ki na yanuyanu lailai.",
    englishDef: "Boat trip; boat travel. Island-hopping by boat is one of Fiji's greatest pleasures — from Port Denarau, visitors can reach outer islands, snorkelling spots, and remote beaches by guided boat tour.",
    example: "Na waqawaqa ki na yanuyanu e marautaka au.",
    exampleTranslation: "The boat trip to the island made me happy.",
    category: "travel",
    tags: ["tourism", "nature"]
  },
  {
    id: 140,
    word: "ivola ni lako",
    phonetic: "ivola ni lako",
    partOfSpeech: "noun phrase",
    fijianDef: "Ko ivola ni lako e vakayacori taka na itikitiki ni lako — na \"itinerary\". E na nona veisiga e dau bilivilidata na vulagi me ra kila na nodra ivola ni lako me rawa ni vakacaucautataki vinaka.",
    englishDef: "Itinerary; travel schedule. A well-planned ivola ni lako makes the difference between a good trip and an unforgettable one — Fiji Tours & Transfers specialises in custom itineraries for every visitor.",
    example: "Na ivola ni lako e caka vinaka.",
    exampleTranslation: "The travel itinerary is well prepared.",
    category: "travel",
    tags: ["travel", "tourism"]
  },
  // ── EXPANSION PACK: Language, Learning & Platform words (141–155) ──────
  {
    id: 141,
    word: "vuli",
    phonetic: "vuli",
    partOfSpeech: "verb",
    fijianDef: "Ko vuli e vakayacori taka na cakacaka ni kila — na veivosaki kina na ivola ka na kena kila. E vakabibi na vuli e na bula ni tamata — na kila e dau laki veiqaravi taka.",
    englishDef: "To learn; to study. The act of gaining knowledge. Vuli is at the heart of this platform — every word you learn brings you closer to the heart of Fijian culture and people.",
    example: "Au via vuli na vosa vakaviti.",
    exampleTranslation: "I want to learn the Fijian language.",
    category: "basics",
    tags: ["essential", "everyday"]
  },
  {
    id: 142,
    word: "kila",
    phonetic: "kila",
    partOfSpeech: "verb / noun",
    fijianDef: "Ko kila e vakayacori taka na veivosaki ni rawa ni kilai na ka — na kena kila. Ko ira na tamata e kila na vosa vakaviti e rawa ni veiqaravi vinaka sara kina na lewe ni vanua.",
    englishDef: "To know; knowledge. Understanding Fijian language and culture opens every door — locals light up when a visitor shows they kila (know) even a few words of the language.",
    example: "Au kila na vosa vakaviti.",
    exampleTranslation: "I know the Fijian language.",
    category: "basics",
    tags: ["essential", "everyday"]
  },
  {
    id: 143,
    word: "vosa vakaviti",
    phonetic: "vosa vakaviti",
    partOfSpeech: "noun phrase",
    fijianDef: "Ko vosa vakaviti e vakayacori taka na vosa dina ni lewenivanua ni Viti — na vosa e ra tukutuku kina na kai Viti. E 300,000 na lewenivanua e ra vosa vakaviti e vuqa na matanitu.",
    englishDef: "Fijian language. The indigenous Austronesian language of Fiji, spoken by around 300,000 people. Learning even basic vosa vakaviti transforms a tourist visit into a genuine cultural connection.",
    example: "Na vosa vakaviti e totoka me kila.",
    exampleTranslation: "The Fijian language is beautiful to learn.",
    category: "basics",
    tags: ["language", "essential"]
  },
  {
    id: 144,
    word: "isausau",
    phonetic: "isausau",
    partOfSpeech: "noun",
    fijianDef: "Ko isausau e vakayacori taka na ivakarau ni dau cakacaka vinaka — na \"prize\" ka na \"reward\". E dau solia na isausau ki na tamata e cakacaka vinaka ka e taukeni tiko na kena kila.",
    englishDef: "Prize; reward; award. The recognition given for achievement and excellence. On this platform, earning isausau motivates daily learning — every quiz win, streak, and mastered word earns its reward.",
    example: "Na isausau e solia ki na tamata e cakacaka vinaka.",
    exampleTranslation: "The prize is given to the person who works well.",
    category: "basics",
    tags: ["achievement", "learning"]
  },
  {
    id: 145,
    word: "turaga",
    phonetic: "turaga",
    partOfSpeech: "noun",
    fijianDef: "Ko turaga e vakayacori taka na tamata e levu na kena mana — na nodra veiliutaki na koro. Na turaga e dau vakabibi na veiqaravi ka na kaukauwa ni bula vakavanua.",
    englishDef: "Chief; person of high rank. Turaga is the highest social title in Fijian society — bestowed through lineage and respected absolutely. On this platform, top learners earn the Turaga title.",
    example: "Na turaga e veiliutaki na koro.",
    exampleTranslation: "The chief leads the village.",
    category: "society",
    tags: ["cultural", "society", "achievement"]
  },
  {
    id: 146,
    word: "ivakarau",
    phonetic: "ivakarau",
    partOfSpeech: "noun",
    fijianDef: "Ko ivakarau e vakayacori taka na nodra veimataivalu ni lewenivanua — na \"culture\" ka na \"tradition\". Na ivakarau ni Viti e bibi ka e totoka — e vakayacori taka na nodra bula na kai Viti.",
    englishDef: "Culture; tradition; customs. The rich ivakarau of Fiji encompasses kava ceremonies, meke dance, lovo feasts, and deep respect for land and sea — the living heritage that every tour visitor encounters.",
    example: "Na ivakarau ni Viti e bibi sara.",
    exampleTranslation: "The culture of Fiji is very important.",
    category: "culture",
    tags: ["cultural", "essential"]
  },
  {
    id: 147,
    word: "dua",
    phonetic: "ndua",
    partOfSpeech: "number / adjective",
    fijianDef: "Ko dua e vakayacori taka na ivolatabu ni dua — na nomuni dua. E dau vakayacori tu na vosa oqo e na vosa vakataucoko. 'Dua ga' e kaya me \"only one\" ka \"just one\".",
    englishDef: "One; a; single. The first number in Fijian — also used as the indefinite article 'a'. 'Dua ga' (just one) perfectly captures the Fijian spirit of savoring one moment, one island, one cup of yaqona at a time.",
    example: "Dua ga na bula!",
    exampleTranslation: "There is only one life!",
    category: "numbers",
    tags: ["essential", "everyday"]
  },
  {
    id: 148,
    word: "rua",
    phonetic: "rua",
    partOfSpeech: "number",
    fijianDef: "Ko rua e vakayacori taka na ivolatabu ni rua — na nomuni rua. E dau vakayacori tu na vosa oqo me vakaraica na veika e rua e na vosa vakataucoko.",
    englishDef: "Two; second. The second number in Fijian. Used in counting, time, and grouping — rua na gone (two children), rua na siga (two days), rua na bilo (two cups of yaqona).",
    example: "E rua na gone i kea.",
    exampleTranslation: "There are two children there.",
    category: "numbers",
    tags: ["essential", "everyday"]
  },
  {
    id: 149,
    word: "tolu",
    phonetic: "tolu",
    partOfSpeech: "number",
    fijianDef: "Ko tolu e vakayacori taka na ivolatabu ni tolu — na nomuni tolu. E dau vakayacori tu na vosa oqo e na ivola ni kena sigatabu.",
    englishDef: "Three; third. The third number in Fijian. 'Tolu na siga' means three days — often how long visitors wish they had stayed longer when they discover the warmth of Fiji.",
    example: "Au tiko e Viti e na siga e tolu.",
    exampleTranslation: "I stayed in Fiji for three days.",
    category: "numbers",
    tags: ["essential", "everyday"]
  },
  {
    id: 150,
    word: "vā",
    phonetic: "vaa",
    partOfSpeech: "number",
    fijianDef: "Ko vā e vakayacori taka na ivolatabu ni vā — na nomuni vā. E dau vakayacori tu na vosa oqo e na kena kina na veika e vā.",
    englishDef: "Four. The fourth number in Fijian. Used across the language in counting, measurement, and time. Vā na aua (four o'clock) — the golden hour on a Fiji beach when the light turns magical.",
    example: "E vā na ika au a kau mai.",
    exampleTranslation: "I brought four fish.",
    category: "numbers",
    tags: ["essential"]
  },
  {
    id: 151,
    word: "lima",
    phonetic: "lima",
    partOfSpeech: "number / noun",
    fijianDef: "Ko lima e vakayacori taka na ivolatabu ni lima — ka e vakayacori tale kina na liga. E dau vakayacori tu na vosa oqo e na kena kina na liga ka na ivolatabu.",
    englishDef: "Five; also hand. Lima means both the number five and the hand — a beautiful linguistic link. 'Lima na siga' means five days — enough time for a proper Fiji holiday adventure.",
    example: "E lima na siga au tiko e Viti.",
    exampleTranslation: "I stayed in Fiji for five days.",
    category: "numbers",
    tags: ["essential", "everyday"]
  },
  {
    id: 152,
    word: "ono",
    phonetic: "ono",
    partOfSpeech: "number",
    fijianDef: "Ko ono e vakayacori taka na ivolatabu ni ono. E dau vakayacori tu na vosa oqo e na vosa vakataucoko me vakaraica na veika e ono.",
    englishDef: "Six. The sixth number in Fijian. In Fijian counting, numbers follow a base-10 system with unique words for 1–9. Ono is also a common name for a type of Fijian fish.",
    example: "E ono na tamata e na waqa.",
    exampleTranslation: "There are six people on the boat.",
    category: "numbers",
    tags: ["essential"]
  },
  {
    id: 153,
    word: "vitu",
    phonetic: "vitu",
    partOfSpeech: "number",
    fijianDef: "Ko vitu e vakayacori taka na ivolatabu ni vitu. E dau vakayacori tu na vosa oqo e na vosa vakataucoko me vakaraica na veika e vitu.",
    englishDef: "Seven. The seventh number in Fijian. 'Vitu na siga' — seven days — is a full week in Fiji, which experienced travellers say is barely enough to scratch the surface of what these islands offer.",
    example: "Na wiki e vitu na siga.",
    exampleTranslation: "A week is seven days.",
    category: "numbers",
    tags: ["essential"]
  },
  {
    id: 154,
    word: "walu",
    phonetic: "walu",
    partOfSpeech: "number",
    fijianDef: "Ko walu e vakayacori taka na ivolatabu ni walu. E dau vakayacori tu na vosa oqo e na vosa vakataucoko. Na walu e vosa tale me vakayacori na ika e rokomoka e Viti.",
    englishDef: "Eight; also a type of Fijian fish (Spanish Mackerel). Walu is both the number eight and a prized reef fish found in Fijian waters — often served at lovo feasts and resort restaurants.",
    example: "Au kani na walu i Viti.",
    exampleTranslation: "I ate walu (Spanish mackerel) in Fiji.",
    category: "numbers",
    tags: ["essential", "food"]
  },
  {
    id: 155,
    word: "ciwa",
    phonetic: "thiwa",
    partOfSpeech: "number",
    fijianDef: "Ko ciwa e vakayacori taka na ivolatabu ni ciwa. E dau vakayacori tu na vosa oqo e na vosa vakataucoko me vakaraica na veika e ciwa.",
    englishDef: "Nine. The ninth number in Fijian. Close to ten — the near-complete feeling of mastering a language one word at a time, almost there, almost fluent in the warmth of Fijian conversation.",
    example: "E ciwa na gone e na vale ni vuli.",
    exampleTranslation: "There are nine children at the school.",
    category: "numbers",
    tags: ["essential"]
  },
  {
    id: 156,
    word: "tini",
    phonetic: "tini",
    partOfSpeech: "number",
    fijianDef: "Ko tini e vakayacori taka na ivolatabu ni tini — na \"tini\" e dau vakayacori tu e na kena muri e na ivolatabu e levu cake. E.g. tini ka dua (11), tini ka rua (12).",
    englishDef: "Ten. The first round number in Fijian — the base of counting. From tini, Fijian numbers build up: tini ka dua (11), tini ka rua (12). Master tini and the whole number system opens up.",
    example: "E tini na lewe ni matavuvale.",
    exampleTranslation: "There are ten members in the family.",
    category: "numbers",
    tags: ["essential"]
  },
  {
    id: 157,
    word: "totoka",
    phonetic: "totoka",
    partOfSpeech: "adjective",
    fijianDef: "Ko totoka e vakayacori taka na ka e raici vinaka — na totoka. E dau vakayacori na vosa oqo ki na vanua, na tamata, ka na ka e raici vinaka sara.",
    englishDef: "Beautiful; lovely; stunning. The Fijian word for beauty in all its forms — a beautiful sunset, a beautiful person, a beautiful island. Visitors to Fiji quickly add totoka to their vocabulary.",
    example: "Na yanuyanu i Viti e totoka sara!",
    exampleTranslation: "The islands of Fiji are absolutely beautiful!",
    category: "descriptive",
    tags: ["everyday", "essential", "tourism"]
  },
  {
    id: 158,
    word: "marau",
    phonetic: "marau",
    partOfSpeech: "adjective / verb",
    fijianDef: "Ko marau e vakayacori taka na loma ni marau — na \"happy\". E dau vakayacori na vosa oqo me vakaraica na loma vinaka. \"Au marau sara\" e kaya me \"I am so happy\".",
    englishDef: "Happy; joyful; glad. Marau is the spirit of every Fiji visit — the infectious happiness that spreads from local communities to every visitor who experiences genuine Fijian warmth.",
    example: "Au marau sara e Viti!",
    exampleTranslation: "I am so happy in Fiji!",
    category: "emotions",
    tags: ["everyday", "essential"]
  },
  {
    id: 159,
    word: "isa lei",
    phonetic: "isa lei",
    partOfSpeech: "phrase / song",
    fijianDef: "Ko Isa Lei e dua na sere e bibi sara e Viti — na sere ni veigaluvi. E dau sere na vosa oqo me vakayacori taka na loloma ka na rarawa ni veigaluvi. Na vulagi e dau rogoca na sere oqo me ra lako tani mai Viti.",
    englishDef: "Isa Lei — Fiji's beloved farewell song. Sung to departing guests at airports, resorts, and village visits, 'Isa Lei' expresses the love and sadness of parting. Hearing it makes every visitor want to return.",
    example: "Ra sere na 'Isa Lei' me ra vakabiuta na vulagi.",
    exampleTranslation: "They sang 'Isa Lei' to farewell the visitors.",
    category: "culture",
    tags: ["cultural", "music", "essential"]
  },
  {
    id: 160,
    word: "sota tale",
    phonetic: "sota tale",
    partOfSpeech: "phrase",
    fijianDef: "Ko sota tale e vakayacori taka na veivosaki ni veisautaki — na \"see you again\". E dau vakayacori na vosa oqo me vakabiuta na tamata ka na vakamoce. E vakayacori taka na lomani ka na sega ni via vakamoce taumada.",
    englishDef: "See you again; until we meet again. The warm Fijian farewell that always leaves the door open for return. Every visitor who hears 'sota tale' at the end of their Fiji tour knows they'll be back.",
    example: "Sota tale! Me lako vinaka!",
    exampleTranslation: "See you again! Travel safely!",
    category: "greetings",
    tags: ["essential", "everyday", "tourism"]
  }
];

const CATEGORIES = [
  { id: "all", label: "All Words" },
  { id: "greetings", label: "Greetings" },
  { id: "food", label: "Food" },
  { id: "people", label: "People" },
  { id: "places", label: "Places" },
  { id: "travel", label: "Travel" },
  { id: "numbers", label: "Numbers" },
  { id: "nature", label: "Nature" },
  { id: "culture", label: "Culture" },
  { id: "emotions", label: "Emotions" },
  { id: "verbs", label: "Verbs" },
  { id: "basics", label: "Basics" },
  { id: "descriptive", label: "Descriptive" },
  { id: "society", label: "Society" },
  { id: "phrases", label: "Phrases" }
];
